# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: libros.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'libros.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clibros.proto\x12\x0cLibroService\x1a\x1bgoogle/protobuf/empty.proto\"L\n\x05Libro\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\r\n\x05\x61utor\x18\x03 \x01(\t\x12\x18\n\x10\x61nio_publicacion\x18\x04 \x01(\x05\"\x1a\n\x0cLibroRequest\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\rLibroResponse\x12\"\n\x05libro\x18\x01 \x01(\x0b\x32\x13.LibroService.Libro\"5\n\x0eLibrosResponse\x12#\n\x06libros\x18\x01 \x01(\x0b\x32\x13.LibroService.Libro\"9\n\x13\x41gregarLibroRequest\x12\"\n\x05libro\x18\x01 \x01(\x0b\x32\x13.LibroService.Libro\"3\n\x14\x41gregarLibroResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"(\n\x15\x45liminarLibroResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"<\n\x16\x41\x63tualizarLibroRequest\x12\"\n\x05libro\x18\x01 \x01(\x0b\x32\x13.LibroService.Libro\"*\n\x17\x41\x63tualizarLibroResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2\xb3\x03\n\rLibrosService\x12I\n\x0cObtenerLibro\x12\x1a.LibroService.LibroRequest\x1a\x1b.LibroService.LibroResponse\"\x00\x12W\n\x0c\x41gregarLibro\x12!.LibroService.AgregarLibroRequest\x1a\".LibroService.AgregarLibroResponse\"\x00\x12H\n\x0cListarLibros\x12\x16.google.protobuf.Empty\x1a\x1c.LibroService.LibrosResponse\"\x00\x30\x01\x12R\n\rEliminarLibro\x12\x1a.LibroService.LibroRequest\x1a#.LibroService.EliminarLibroResponse\"\x00\x12`\n\x0f\x41\x63tualizarLibro\x12$.LibroService.ActualizarLibroRequest\x1a%.LibroService.ActualizarLibroResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libros_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIBRO']._serialized_start=59
  _globals['_LIBRO']._serialized_end=135
  _globals['_LIBROREQUEST']._serialized_start=137
  _globals['_LIBROREQUEST']._serialized_end=163
  _globals['_LIBRORESPONSE']._serialized_start=165
  _globals['_LIBRORESPONSE']._serialized_end=216
  _globals['_LIBROSRESPONSE']._serialized_start=218
  _globals['_LIBROSRESPONSE']._serialized_end=271
  _globals['_AGREGARLIBROREQUEST']._serialized_start=273
  _globals['_AGREGARLIBROREQUEST']._serialized_end=330
  _globals['_AGREGARLIBRORESPONSE']._serialized_start=332
  _globals['_AGREGARLIBRORESPONSE']._serialized_end=383
  _globals['_ELIMINARLIBRORESPONSE']._serialized_start=385
  _globals['_ELIMINARLIBRORESPONSE']._serialized_end=425
  _globals['_ACTUALIZARLIBROREQUEST']._serialized_start=427
  _globals['_ACTUALIZARLIBROREQUEST']._serialized_end=487
  _globals['_ACTUALIZARLIBRORESPONSE']._serialized_start=489
  _globals['_ACTUALIZARLIBRORESPONSE']._serialized_end=531
  _globals['_LIBROSSERVICE']._serialized_start=534
  _globals['_LIBROSSERVICE']._serialized_end=969
# @@protoc_insertion_point(module_scope)
