# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import libros_pb2 as libros__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in libros_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibrosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerLibro = channel.unary_unary(
                '/LibroService.LibrosService/ObtenerLibro',
                request_serializer=libros__pb2.LibroRequest.SerializeToString,
                response_deserializer=libros__pb2.LibroResponse.FromString,
                _registered_method=True)
        self.AgregarLibro = channel.unary_unary(
                '/LibroService.LibrosService/AgregarLibro',
                request_serializer=libros__pb2.AgregarLibroRequest.SerializeToString,
                response_deserializer=libros__pb2.AgregarLibroResponse.FromString,
                _registered_method=True)
        self.ListarLibros = channel.unary_stream(
                '/LibroService.LibrosService/ListarLibros',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=libros__pb2.LibrosResponse.FromString,
                _registered_method=True)
        self.EliminarLibro = channel.unary_unary(
                '/LibroService.LibrosService/EliminarLibro',
                request_serializer=libros__pb2.LibroRequest.SerializeToString,
                response_deserializer=libros__pb2.EliminarLibroResponse.FromString,
                _registered_method=True)
        self.ActualizarLibro = channel.unary_unary(
                '/LibroService.LibrosService/ActualizarLibro',
                request_serializer=libros__pb2.ActualizarLibroRequest.SerializeToString,
                response_deserializer=libros__pb2.ActualizarLibroResponse.FromString,
                _registered_method=True)


class LibrosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ObtenerLibro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgregarLibro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarLibros(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarLibro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarLibro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibrosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerLibro': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerLibro,
                    request_deserializer=libros__pb2.LibroRequest.FromString,
                    response_serializer=libros__pb2.LibroResponse.SerializeToString,
            ),
            'AgregarLibro': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarLibro,
                    request_deserializer=libros__pb2.AgregarLibroRequest.FromString,
                    response_serializer=libros__pb2.AgregarLibroResponse.SerializeToString,
            ),
            'ListarLibros': grpc.unary_stream_rpc_method_handler(
                    servicer.ListarLibros,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=libros__pb2.LibrosResponse.SerializeToString,
            ),
            'EliminarLibro': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarLibro,
                    request_deserializer=libros__pb2.LibroRequest.FromString,
                    response_serializer=libros__pb2.EliminarLibroResponse.SerializeToString,
            ),
            'ActualizarLibro': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarLibro,
                    request_deserializer=libros__pb2.ActualizarLibroRequest.FromString,
                    response_serializer=libros__pb2.ActualizarLibroResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LibroService.LibrosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LibroService.LibrosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LibrosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObtenerLibro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LibroService.LibrosService/ObtenerLibro',
            libros__pb2.LibroRequest.SerializeToString,
            libros__pb2.LibroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgregarLibro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LibroService.LibrosService/AgregarLibro',
            libros__pb2.AgregarLibroRequest.SerializeToString,
            libros__pb2.AgregarLibroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarLibros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/LibroService.LibrosService/ListarLibros',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            libros__pb2.LibrosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarLibro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LibroService.LibrosService/EliminarLibro',
            libros__pb2.LibroRequest.SerializeToString,
            libros__pb2.EliminarLibroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarLibro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LibroService.LibrosService/ActualizarLibro',
            libros__pb2.ActualizarLibroRequest.SerializeToString,
            libros__pb2.ActualizarLibroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
